# Generated by Django 4.1.5 on 2023-01-27 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book_outlet", "0004_country_alter_address_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country", options={"verbose_name_plural": "countries"},
        ),
    ]
