# Generated by Django 4.1.5 on 2023-01-27 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book_outlet", "0005_alter_country_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country", options={"verbose_name_plural": "Countries"},
        ),
    ]
